// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saaoxoiqyaoneecqirzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYW94b2lxeWFvbmVlY3Fpcnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDM1NDUsImV4cCI6MjA3MDkxOTU0NX0.HgUr2_MePgkmEMhXRGV3DUkQ5GFe4L0V-hPGN1abO1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});